name: Android CI
# from https://medium.com/@wkrzywiec/github-actions-for-android-first-approach-f616c24aa0f9

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: set up JDK 1.8
      uses: actions/setup-java@master
      with:
        java-version: 1.8
    - name: Unit tests
      run: bash ./gradlew test --stacktrace
